export const inputs = {
  name: document.querySelector<HTMLInputElement>("#name")!,
  title: document.querySelector<HTMLInputElement>("#title")!,
  pronouns: document.querySelector<HTMLInputElement>("#pronounsField")!,
  email: document.querySelector<HTMLInputElement>("#email")!,
  phone: document.querySelector<HTMLInputElement>("#phone")!,
  linkedinPers: document.querySelector<HTMLInputElement>("#linkedinPers")!,
  logo: document.querySelector<HTMLInputElement>("#logo")!,
  address: document.querySelector<HTMLTextAreaElement>("#address")!,
  orgName: document.querySelector<HTMLInputElement>("#orgName")!,
  website: document.querySelector<HTMLInputElement>("#website")!,
  facebook: document.querySelector<HTMLInputElement>("#facebook")!,
  instagram: document.querySelector<HTMLInputElement>("#instagram")!,
  x: document.querySelector<HTMLInputElement>("#twitter")!,
  bluesky: document.querySelector<HTMLInputElement>("#bluesky")!,
  youtube: document.querySelector<HTMLInputElement>("#youtube")!,
  linkedinOrg: document.querySelector<HTMLInputElement>("#linkedinOrg")!,
  tiktok: document.querySelector<HTMLInputElement>("#tiktok")!,
  flickr: document.querySelector<HTMLInputElement>("#flickr")!,
  whatsapp: document.querySelector<HTMLInputElement>("#whatsapp")!,
  skype: document.querySelector<HTMLInputElement>("#skype")!,
};
