export const inputs = {
    name: document.getElementById("name") as HTMLInputElement,
    title: document.getElementById("title") as HTMLInputElement,
    pronouns: document.getElementById("pronounsField") as HTMLInputElement,
    email: document.getElementById("email") as HTMLInputElement,
    phone: document.getElementById("phone") as HTMLInputElement,
    linkedinPers: document.getElementById("linkedinPers") as HTMLInputElement,
    logo: document.getElementById("logo") as HTMLInputElement,
    address: document.getElementById("address") as HTMLTextAreaElement,
    orgName: document.getElementById("orgName") as HTMLInputElement,
    website: document.getElementById("website") as HTMLInputElement,
    facebook: document.getElementById("facebook") as HTMLInputElement,
    instagram: document.getElementById("instagram") as HTMLInputElement,
    x: document.getElementById("twitter") as HTMLInputElement,
    bluesky: document.getElementById("bluesky") as HTMLInputElement,
    youtube: document.getElementById("youtube") as HTMLInputElement,
    linkedinOrg: document.getElementById("linkedinOrg") as HTMLInputElement,
    tiktok: document.getElementById("tiktok") as HTMLInputElement,
    flickr: document.getElementById("flickr") as HTMLInputElement,
    whatsapp: document.getElementById("whatsapp") as HTMLInputElement,
    skype: document.getElementById("skype") as HTMLInputElement,
};
